spring:
  # 数据源信息
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          # 配置连接数据库的各个信息
          type: ${spring.datasource.type}
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/dream_starter_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
          username: root
          password: 123456
        slave_1:
          lazy: true
          type: ${spring.datasource.type}
          driver-class-name: com.mysql.cj.jdbc.Driver
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
          username:
          password:
mybatis-plus:
  # 配置mapper的扫描路径
  mapperPackage: com.dream.**.mapper
  configuration:
    # 设置日志，打印执行的SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl